name: Rust

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    schedule:
        - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Update
      run: rustup update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose